Fix cache metrics and minor refactor on zmetrics
Zondax/golem pull request #82
Opened 2024-03-05 19:10 UTC by lucaslopezf

2024-03-05 23:53 UTC, emmanuelm41 reviewed
Let's fix ci first

2024-03-06 18:38 UTC, emmanuelm41 requested changes
Left an important comment!

2024-03-06 18:38 UTC, emmanuelm41 commented on pkg/metrics/register.go
> +	labels = append(labels, appNameLabel, appVersionLabel, appRevisionLabel)
appName can be a label, but appVersion and appRevison, as well as appStartUp should be a metric itself

2024-03-06 19:14 UTC, emmanuelm41 commented on pkg/zrouter/zrouter.go
> +	appStartMetric    = "app_start"
`uptime` would be better name. What do you think?

2024-03-06 19:16 UTC, emmanuelm41 approved these changes

2024-03-06 19:32 UTC, lucaslopezf commented on pkg/metrics/register.go
> +	APPNameLabel = "app_name"
No, we need the constant to be public, not private

2024-03-06 19:37 UTC, merged

2024-03-07 12:01 UTC, emmanuelm41 commented on pkg/metrics/register.go
> +	APPNameLabel = "app_name"
But it could be AppNameLabel, instead of APPNameLabel!